### ISSUE TITLE
[BUG] relatedImages are incomplete in the published bundle.

### ISSUE THREAD

**Issue by libesz** [istio-ecosystem/sail-operator#282] opened 2024-08-14 19:31 UTC
### Is this the right place to submit this?

- [X] This is not a question about how to use the sail-operator

### Bug Description

After closing https://github.com/istio-ecosystem/sail-operator/issues/216 and https://github.com/istio-ecosystem/sail-operator/pull/243, it is expected to have a complete set of `relatedImages` in the published operator catalog bundle, which may be ever installed by the operator. In the 14th Aug nightly build, the only new image (compared to earlier bundles) is ztunnel, while pilot, proxyv2 and cni appears to be missing. The incomplete `relatedImages` section breaks any image mirroring effort based on `opm` or other catalog index based tooling.
The complete `relatedImages` section of the current nightly build is:
```json
    "relatedImages": [
        {
            "name": "v1_22_3.ztunnel",
            "image": "docker.io/istio/ztunnel:1.22.3"
        },
        {
            "name": "",
            "image": "gcr.io/kubebuilder/kube-rbac-proxy:v0.16.0"
        },
        {
            "name": "",
            "image": "quay.io/community-operator-pipeline-prod/sailoperator@sha256:4b84e4c19956e198e9d10c3f2314ebdfca3cccd0e3efe36291ea7d98cdfd6017"
        },
        {
            "name": "",
            "image": "quay.io/maistra-dev/sail-operator:0.1-nightly-2024-08-14"
        }
    ]
```

### Operator Version

sailoperator.v0.1.0-nightly-2024-08-14

**Comment by dgn** [comment] 2024-08-15 11:17
it's really strange- I can't reproduce this on my machine. whenever I run the target, all the relatedImages are filled in correctly

**Comment by dgn** [comment] 2024-08-16 08:52
we most likely found the issue... outdated version of `yq` in build container [which has a bug we're affected by](https://github.com/mikefarah/yq/issues/2068
). updating the build container now

**Comment by dgn** [comment] 2024-08-22 08:50
the latest nightly builds and the [0.1.0-rc1 CSV](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/05980c9a2dee1af345a7d87a55828768010e7603/operators/sailoperator/0.1.0-rc.1/manifests/sailoperator.clusterserviceversion.yaml#L751-L767) have the correct relatedImages, closing this

**Closed by dgn** 2024-08-22 08:50 UTC
Labels: bug
